# run parameters
initial_pose_std_xy: 0.2
initial_pose_std_theta: 0.2617
goal_tolerance: 0.4
run_timeout: 3000.0
waypoint_timeout: 600
robot_radius: 0.2

# topic names
scan_topic: /scan_gt_mb
ground_truth_pose_topic: /base_footprint_gt

# service names
save_map_service: /slam_toolbox/save_map
serialize_map_service: /slam_toolbox/serialize_map

# action names
navigate_to_pose_action: /move_base

# frame names
fixed_frame: map
mapper_odom_frame: odom_gt_st
robot_base_frame: base_link_gt_st
gt_base_frame: base_footprint_gt_mb
mapper_base_frame: base_footprint_gt_st
