ground_truth_mapping_supervisor:
  ros__parameters:

    # run parameters
    initial_pose_std_xy: 0.2
    initial_pose_std_theta: 0.2617
    goal_tolerance: 0.4
    run_timeout: 10800.0
    ps_snapshot_period: 10.0
    write_estimated_poses_period: 0.1

    # topic names
    scan_topic: /scan_gt
    ground_truth_pose_topic: /ground_truth/base_footprint/odom

    # service names
    lifecycle_manager_service: /lifecycle_manager/manage_nodes
    global_costmap_get_parameters_service: /local_costmap/local_costmap/get_parameters
    save_map_service: /save_map
    serialize_map_service: /serialize_map

    # action names
    navigate_to_pose_action: /NavigateToPose

    # frame names
    fixed_frame: map

    # gazebo entity names
    robot_entity_name: robot
